{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now+3h" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "always_discharge_percent",
    "label": "Always Discharge SOC",
    "query": {
     "query": "SELECT \"always_allow_discharge_limit_percent\" FROM \"autogen\".\"batcontrol\" WHERE $timeFilter LIMIT 1"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Reserved energy vs stored",
   "type": "gauge",
   "description": "This describes the offset of battery content vs. the relevant parts of the load profile",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "stored",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "select": [
      [
       { "params": [ "stored_usable_energy_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "reserved",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "select": [
      [
       { "params": [ "reserved_energy_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batcontrol Mode",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "select": [
      [
       { "params": [ "mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SOC",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "query": "SELECT last(\"SOC\") FROM \"autogen\".\"batcontrol\" WHERE $timeFilter GROUP BY time(5m) fill(previous) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "SOC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOC%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "alias": "SOC %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "select": [
      [
       { "params": [ "SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MIN_SOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "batcontrol-inverter-0",
     "select": [
      [
       { "params": [ "min_soc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Max Charging from Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "select": [
      [
       {
        "params": [
         "max_charging_from_grid_limit_percent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Always Discharge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "query": "SELECT \"always_allow_discharge_limit_percent\" FROM \"autogen\".\"batcontrol\" WHERE $timeFilter",
     "select": [
      [
       {
        "params": [
         "always_allow_discharge_limit_percent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Locked",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "select": [
      [
       { "params": [ "mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "mode", "operator": "Is", "value": "0" }
     ]
    },
    {
     "alias": "Charging",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "select": [
      [
       { "params": [ "mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "+101" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "mode", "operator": "Is", "value": "-1" }
     ]
    },
    {
     "alias": "Discharge",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "query": "SELECT 100 as x, last(mode) FROM \"autogen\".\"batcontrol\" WHERE (\"mode\" = 10) AND $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "mode", "operator": "Is", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Calculated needed capacity vs. stored energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Reserved",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "select": [
      [
       { "params": [ "reserved_energy_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Stored",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "select": [
      [
       { "params": [ "stored_energy_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Max Capacity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "batcontrol-inverter-0",
     "select": [
      [
       { "params": [ "max_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Usable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "batcontrol",
     "select": [
      [
       { "params": [ "stored_usable_energy_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Expected Load",
   "type": "timeseries",
   "description": "Negative is overcapacity which can be stored",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "batcontrol-net_consumption",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "alias": "Costs per kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "batcontrol-prices",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"batcontrol-prices\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Expected Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Solar power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "batcontrol-production",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Expected Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "batcontrol-consumption",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}